name: dirham_symbol
description: The complete UAE Dirham (AED) currency toolkit for Flutter. Features official vector & SVG symbols, e-commerce sale prices, animated counters, currency text fields, and extensions.
version: 0.4.2
homepage: https://github.com/nadeerep07/dirham-symbol
repository: https://github.com/nadeerep07/dirham-symbol
issue_tracker: https://github.com/nadeerep07/dirham-symbol/issues
topics:
  - currency
  - uae
  - fintech
  - ecommerce
  - formatting

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  intl: ^0.20.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/uae-dirham.svg
    - screenshots/